language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - dependencies=locked
  - dependencies=highest
  - dependencies=lowest

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install -n

before_script:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --prefer-stable -n; fi;

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

notifications:
  email:
    on_success: change
    on_failure: always
